### PR TITLE
Update and rename DOCKER_mac_setup.MD to DOCKER_mac_setup_external_fu…

### PR DESCRIPTION
**Pull request by PuraVlda**
…ll_node.MD

I did not use the same process as the previous guide and wanted to offer my solutions.  Thanks to Alpha Zeta for the original creation of this Page.

### CODE REVIEW

**Comment by PuraVlda** [comment]
Well, not great at how GitHub works.  Dont really want to rename, wanted to change and add my way as another option...... hmmmm

**Comment by PuraVlda** [comment]
Thanks.  Once reviewed, let me know if something on my end needs corrected to merge in, again, fresh to the git commits.

**Comment by kenshin-samourai** [comment]
@pxsocs a documentation for the 3 setups would be great if you think that option 3 is a good option for mac users

**Comment by pxsocs** [comment]
Since the original file was deleted, I've submitted a new pull requests that includes all 3 alternatives, including the one from @PuraVlda:
[Pull Request #50](https://github.com/Samourai-Wallet/samourai-dojo/pull/50)

**Pull request closed without merging**
